config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'welcome#index'
  get 'about', to: 'about#show'
  get 'history', to: 'history#show'

  # hardcoded legacy redirect
  get 'lineages', to: 'lineages#index'

  resources :organisms, param: :name do
    resources :lineage_variants, only: [:index]
    resources :lineages, param: :name, constraints: { name: /[A-z0-9.]+/ }
    resources :primer_sets, only: [:index]
    resource :primer_variant_summary, only: [:show]
  end

  resources :oligos
  resources :users
  resources :primer_set_subscriptions, only: [:create, :destroy]
  resources :primer_sets, only: [:new, :show, :create, :destroy, :update, :edit]
end

app/models/organism.rb
# frozen_string_literal: true

class Organism < ApplicationRecord
  has_many :blast_hits, dependent: :destroy
  has_many :primer_sets, dependent: :destroy
  has_many :organism_taxa, dependent: :destroy

  def to_s
    name
  end

  def full_name
    name + (self.alias.blank? ? '' : " (#{self.alias})")
  end

  def primer_sets_config
    config = {
      "data_server": ENV['IGV_DATA_SERVER'],
      "organism_slug": slug,
      "organism_name": name
    }

    tracks_url = URI("#{config[:data_server]}/#{config[:organism_slug]}/config/tracks.json")

    begin
      primer_sets = JSON.parse(Net::HTTP.get(tracks_url)).invert
    rescue JSON::ParserError
      # cannot parse JSON properly, treat it as empty
      primer_sets = {}
    end

    [config, primer_sets]
  end

  def lineage_variants_data(data_server, organism_slug)
    tracks_req = HTTParty.get("#{data_server}/#{organism_slug}/config/tracks.json")
    defaults_req = HTTParty.get("#{data_server}/#{organism_slug}/defaults.json")
    lineages_req = HTTParty.get("#{data_server}/#{organism_slug}/config/lineage_sets.json")

    unless tracks_req.code == 200 && defaults_req.code == 200 && lineages_req.code == 200
      # data_fetched, @primer_sets, @default_tracks, @lineage_sets, @default_lineage
      return { data_fetched: false }
    end

    process_lineage_variants_data tracks_req.body, defaults_req.body, lineages_req.body
  end

  def process_lineage_variants_data(tracks_json, defaults_json, lineages_json)
    primer_sets = JSON.parse(tracks_json)

    defaults_parsed = JSON.parse(defaults_json)
    default_tracks = defaults_parsed['tracks']
    default_lineage = defaults_parsed['lineage']

    lineage_sets = JSON.parse(lineages_json)

    { data_fetched: true, primer_sets:, default_tracks:, lineage_sets:,
      default_lineage: }
  end
end

app/controllers/organisms_controller.rb
# frozen_string_literal: true

class OrganismsController < ApplicationController
  load_and_authorize_resource
  before_action :set_organism, only: %i[show edit update destroy]

  # GET /organisms
  # GET /organisms.json
  def index
    organisms = Organism.all
    @organism_data = []
    organisms.each do |organism|
      @organism_data << { 'organism': organism, 'taxa': OrganismTaxon.where(organism_id: organism.id) }
    end
  end

  # GET /organisms/1
  # GET /organisms/1.json
  def show
    @organism = Organism.find_by(slug: params[:name])

    @config, @primer_sets = @organism.primer_sets_config

    variants_url = URI("#{@config[:data_server]}/#{@config[:organism_slug]}/lineage_variants/all.bed")

    @config[:variants_exist] = (Net::HTTP.get_response(URI(variants_url)).code == '200')
  end

  # GET /organisms/new
  def new
    @organism = Organism.new
  end

  # GET /organisms/1/edit
  def edit; end

  # POST /organisms
  # POST /organisms.json
  def create
    @organism = Organism.new(organism_params)

    respond_to do |format|
      if @organism.save
        format.html { redirect_to @organism, notice: 'Organism was successfully created.' }
        format.json { render :show, status: :created, location: @organism }
      else
        format.html { render :created }
        format.json { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisms/1
  # PATCH/PUT /organisms/1.json
  def update
    respond_to do |format|
      if @organism.update(organism_params)
        format.html { redirect_to @organism, notice: 'Organism was successfully updated.' }
        format.json { render :show, status: :ok, location: @organism }
      else
        format.html { render :edit }
        format.json { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisms/1
  # DELETE /organisms/1.json
  def destroy
    @organism.destroy
    respond_to do |format|
      format.html { redirect_to organisms_url, notice: 'Organism was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_organism
    @organism = Organism.find_by(name: params[:name])
  end

  # Only allow a list of trusted parameters through.
  def organism_params
    params.require(:organism).permit(:name, :alias, :slug)
  end

  def to_param
    name
  end
end

app/views/organisms/_form.html.erb
<%= form_with(model: organism, local: true) do |form| %>
  <% if organism.errors.any? %>
    <div class="notification is-warning">
      <h2><%= pluralize(organism.errors.count, "error") %> prohibited this organism from being saved:</h2>

      <ul>
        <% organism.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :name %>
    </div>
    <div class="control field-body">
      <%= form.text_field :name %>
      <%= form.text_field :alias, placeholder: 'Alias' %>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :ncbi_taxon_id %>
    </div>
    <div class="control field-body">
      <%= form.number_field :ncbi_taxon_id %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-primary"%>
  </div>
<% end %>

app/views/organisms/edit.html.erb
<h1>Editing Organism</h1>

<%= render 'form', organism: @organism %>

<%= link_to 'Show', @organism %> |
<%= link_to 'Back', organisms_path %>

app/views/organisms/index.html.erb
<h1>Organisms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ncbi taxa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organism_data.each do |organism| %>
      <tr>
        <td><%= organism[:organism].full_name %></td>
        <td><%= organism[:taxa].pluck(:ncbi_taxon_id).join ',' %></td>
        <td><%= link_to 'Show', organism_path(organism[:organism].name) %></td>
        <td><%= link_to 'Edit', edit_organism_path(organism[:organism].name) %></td>
        <td><%= link_to 'Destroy', organism_path(organism[:organism].name), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organism', new_organism_path %>

app/views/organisms/new.html.erb
<h1>New Organism</h1>

<%= render 'form', organism: @organism %>

<%= link_to 'Back', organisms_path %>

app/views/organisms/show.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "organisms_show" %>
<% end %>

<h1 class="title">Organism: <%= @organism.full_name %> </h1>


<div class="tile">
  <strong>NCBI Taxonomy IDs:&nbsp;</strong>
  <% taxa_count = @organism.organism_taxa.length %>
  <% i = 0 %>
  <% taxa_str = '' %>
  <% @organism.organism_taxa.each do |organism_taxon| %>
    <% taxa_str += link_to organism_taxon.ncbi_taxon_id, "https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=#{organism_taxon.ncbi_taxon_id}" %>
    <% if i < taxa_count-1 # don't put a comma after the last taxon %>
      <% taxa_str += ',&nbsp;' %>
    <% end %>
    <% i += 1 %>
  <% end %>
  <%= raw taxa_str %>
</div>

<hr/>
<h2 class="title">IGV Visualization:</h2>

<p id="config" class="invisible"><%= @config.to_json %></p>

<div id="igv" class="igv_div"></div>

<% unless @config[:variants_exist] %>
  <p>Variants will be shown once they are processed.</p>
<% end %>


<hr/>

<ul>
  <li><%= link_to 'Primer Sets', organism_primer_sets_path(@organism.slug) %></li>
  <li><%= link_to 'Lineages', organism_lineages_path(@organism.slug) %></li>
  <li><%= link_to 'Lineage Variants', organism_lineage_variants_path(@organism.slug) %></li>
  <% if @organism.slug == 'sars-cov-2' %>
    <li><%= link_to 'Primer Variant Summary', organism_primer_variant_summary_url(@organism.slug) %></li>
  <% else %>
    <li>Primer Variant Summary - Coming Soon!</li>
  <% end %>
</ul>