config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'welcome#index'
  get 'about', to: 'about#show'
  get 'history', to: 'history#show'

  # hardcoded legacy redirect
  get 'lineages', to: 'lineages#index'

  resources :organisms, param: :name do
    resources :lineage_variants, only: [:index]
    resources :lineages, param: :name, constraints: { name: /[A-z0-9.]+/ }
    resources :primer_sets, only: [:index]
    resource :primer_variant_summary, only: [:show]
  end

  resources :oligos
  resources :users
  resources :primer_set_subscriptions, only: [:create, :destroy]
  resources :primer_sets, only: [:new, :show, :create, :destroy, :update, :edit]
end

app/models/lineage.rb
# frozen_string_literal: true

class Lineage < ApplicationRecord
  belongs_to :organism
  has_many :lineage_calls, dependent: :destroy
  has_many :fasta_records, through: :lineage_calls

  def self.external_link_url(organism, lineage_name)
    # expand this with new organisms as support is added for them
    case organism.slug
    when 'sars-cov-2'
      "https://outbreak.info/situation-reports?pango=#{lineage_name}"
    end
  end

  def self.parse(calls_csv, organism, caller_id)
    raise "Unable to find calls file #{calls_csv}" unless File.exist?(calls_csv)

    new_lineage_names = Set[] # new empty set
    record_count = 0

    File.readlines(calls_csv).each do |line|
      next if line.start_with?('taxon,', 'seqName,')

      record_count += 1
      new_lineage = parse_record(line)
      new_lineage_names.add new_lineage unless new_lineage.nil?
    end

    # if there are no records (not only pre-existing lineages, but nothing at all)
    raise "Unable to parse any records from #{calls_csv}" if record_count.zero?

    new_lineages = []

    new_lineage_names.each do |lineage_name|
      new_lineages << Lineage.new(name: lineage_name, caller_name: LineageCaller.find_by(id: caller_id).name,
                                  organism_id: organism.id, external_link: external_link_url(organism, lineage_name))
    end

    new_lineages
  end

  def self.parse_record(line)
    fields = line.chomp.split(',')
    ActiveRecord::Base.logger.info fields if line.chomp.split("\t")[1].blank? || fields.nil?

    # prevent trying to re-add lineages that are already in the database
    if Lineage.exists? name: fields[1]
      nil
    else
      fields[1]
    end
  end
end

app/controllers/lineages_controller.rb
# frozen_string_literal: true

class LineagesController < ApplicationController
  def index
    authorize! :index, LineagesController
    if params.key? :organism_name
      @organism = Organism.find_by(slug: params[:organism_name])

      query = <<-SQL
        SELECT name, times_seen, last_seen FROM lineage_info WHERE organism_id=?;
      SQL
      @lineages = ActiveRecord::Base.connection.execute(ActiveRecord::Base.sanitize_sql([query, @organism.id])).to_a
    else
      # hardcoded legacy redirect
      redirect_to organism_lineage_variants_url(Organism.find_by(slug: 'sars-cov-2').slug), status: :moved_permanently
    end
  end

  def show
    authorize! :show, LineagesController
    @organism = Organism.find_by(name: params[:organism_name])
    @lineage = Lineage.find_by(name: params[:name])
    query = <<-SQL
      SELECT times_seen, first_seen, last_seen FROM lineage_info WHERE organism_id=? AND name=?;
    SQL
    # first because there should only be one record
    @lineage_info = ActiveRecord::Base.connection.execute(ActiveRecord::Base.sanitize_sql([query, @organism.id,
                                                                                           @lineage.name])).to_a.first
  end

  def to_param
    name
  end
end

app/views/lineages/index.html.erb
<h1 class="title">Lineages for <%= @organism.full_name %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last Seen</th>
      <th>Times Seen</th>
    </tr>
  </thead>

  <tbody>
    <% @lineages.each do |lineage| %>
    <% next if lineage['name'] == "Unassigned" %>
      <tr>
        <td><a href="<%= organism_lineage_url(@organism.name, lineage['name']) %>"><%= lineage['name'] %></a></td>
        <td><%= lineage['last_seen'].nil? ? 'N/A' : lineage['last_seen'] %></td>
        <td><%= lineage['times_seen'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lineages/show.html.erb
<h1 class="title"><%= @lineage.organism %> lineage <%= @lineage.name %> </h1>

<h3 class="title">Overview:</h3>

<p><span class="bold-text">Sequences seen:</span> <%= @lineage_info['times_seen'] %></p>
<br>

<p><span class="bold-text">First seen on:</span> <%= @lineage_info['first_seen'].nil? ? 'N/A' : @lineage_info['first_seen'] %></p>

<p><span class="bold-text">Last seen on:</span> <%= @lineage_info['last_seen'].nil? ? 'N/A' : @lineage_info['last_seen'] %></p>

<% unless @lineage.external_link.nil? %>
<br>
<p><span class="bold-text">More data:</span> <a href="<%= @lineage.external_link %>"><%= @lineage.external_link %></a></p>
<% end %>

<br>

<p><span class="bold-text">Note:</span> In the above data, "seen" refers to the date the sample was collected, unless that date was not provided for a sequence, in which case it refers to the date it was submitted to NCBI.</p>