config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'welcome#index'
  get 'about', to: 'about#show'
  get 'history', to: 'history#show'

  # hardcoded legacy redirect
  get 'lineages', to: 'lineages#index'

  resources :organisms, param: :name do
    resources :lineage_variants, only: [:index]
    resources :lineages, param: :name, constraints: { name: /[A-z0-9.]+/ }
    resources :primer_sets, only: [:index]
    resource :primer_variant_summary, only: [:show]
  end

  resources :oligos
  resources :users
  resources :primer_set_subscriptions, only: [:create, :destroy]
  resources :primer_sets, only: [:new, :show, :create, :destroy, :update, :edit]
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# this is the landing page for the application
class WelcomeController < ApplicationController
  def index
    authorize! :show, WelcomeController
  end
end

app/views/welcome/index.html.erb
<article class="message is-small">
  <div class="message-header">
    <p>Welcome!</p>
  </div>
  <div class="message-body">
    This system continually monitors registered primer sets for overlapping variants in sequences from
    <a href="https://www.ncbi.nlm.nih.gov/genbank/">NCBI GenBank®</a>.
    <%= link_to "Logged in", new_user_session_path %> users can propose new primer sets and subscribe for notifications.
  </div>
</article>

<h1 class="title is-4 is-spaced">Organisms Overview</h1>

<hr>
<div class="columns">

  <% i=0 %>

  <% Organism.where(public: true).each do |organism| %>
      <% if i%3 == 0 # start a new row every 3 %>
        </div>
        <hr>
        <div class="columns">
      <% end %>
      <div class="column">
        <h1 class="subtitle"><%= organism.name %></h1>
        <aside class="menu">
          <p class="menu-label">
            Tools
          </p>
          <ul class="menu-list">
            <li><a href="<%= organism_url(organism.slug) %>">Overview</a></li>
            <li><a href="<%= organism_primer_sets_url(organism.slug) %>">Primer Sets (<%=PrimerSet.where(organism_id: organism.id).count %>)</a></li>
            <li><a href="<%= organism_lineages_url(organism.slug) %>">Lineages (<%=Lineage.where(organism_id: organism.id).count %>)</a></li>
            <li><a href="<%= organism_lineage_variants_url(organism.slug) %>">Lineage Variants</a></li>
            <li>
              <% if organism.slug == 'sars-cov-2' %>
                <a href="<%= organism_primer_variant_summary_url(organism.slug) %>">Primer Variant Summary</a>
              <% else %>
                <a class="is-disabled">Primer Variant Summary - Coming Soon!</a>
              <% end %>
                </li>
          </ul>
        </aside>
        <% i=i+1 %>
      </div>
  <% end %>
</div>