config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'welcome#index'
  get 'about', to: 'about#show'
  get 'history', to: 'history#show'

  # hardcoded legacy redirect
  get 'lineages', to: 'lineages#index'

  resources :organisms, param: :name do
    resources :lineage_variants, only: [:index]
    resources :lineages, param: :name, constraints: { name: /[A-z0-9.]+/ }
    resources :primer_sets, only: [:index]
    resource :primer_variant_summary, only: [:show]
  end

  resources :oligos
  resources :users
  resources :primer_set_subscriptions, only: [:create, :destroy]
  resources :primer_sets, only: [:new, :show, :create, :destroy, :update, :edit]
end

app/models/oligo.rb
# frozen_string_literal: true

class Oligo < ApplicationRecord
  belongs_to :primer_set
  has_many :blast_hits, dependent: :destroy
  has_many :oligo_alignment_positions, dependent: :destroy

  enum category: { F3: 'F3', FIP: 'FIP', LF: 'LF', LB: 'LB', BIP: 'BIP', B3: 'B3',
                   Forward: 'Forward', Probe: 'Probe', Reverse: 'Reverse' }

  validates :short_name, length: 1..5, allow_blank: true

  validates :sequence, presence: true,
                       format: { with: /\A([ATUCGWSMKRYBDHVN]|\s)*\z/i, message: 'contains invalid bases' }

  validates :name, presence: true

  def to_s
    "#{name}: #{sequence}"
  end
end

app/controllers/oligos_controller.rb
# frozen_string_literal: true

class OligosController < ApplicationController
  load_and_authorize_resource
  before_action :set_oligo, only: %i[show edit update destroy]

  # GET /oligos
  # GET /oligos.json
  def index
    @oligos = Oligo.all
  end

  # GET /oligos/1
  # GET /oligos/1.json
  def show; end

  # GET /oligos/new
  def new
    @oligo = Oligo.new
  end

  # GET /oligos/1/edit
  def edit; end

  # POST /oligos
  # POST /oligos.json
  def create
    @oligo = Oligo.new(oligo_params)

    respond_to do |format|
      if @oligo.save
        format.html { redirect_to @oligo, notice: 'Oligo was successfully created.' }
        format.json { render :show, status: :created, location: @oligo }
      else
        format.html { render :created }
        format.json { render json: @oligo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oligos/1
  # PATCH/PUT /oligos/1.json
  def update
    respond_to do |format|
      if @oligo.update(oligo_params)
        format.html { redirect_to @oligo, notice: 'Oligo was successfully updated.' }
        format.json { render :show, status: :ok, location: @oligo }
      else
        format.html { render :edit }
        format.json { render json: @oligo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oligos/1
  # DELETE /oligos/1.json
  def destroy
    @oligo.destroy
    respond_to do |format|
      format.html { redirect_to oligos_url, notice: 'Oligo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_oligo
    @oligo = Oligo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def oligo_params
    params.require(:oligo).permit(%i[id primer_set_id name short_name
                                     locus category sequence])
  end
end

app/views/oligos/_form.html.erb
<%= form_with(model: oligo, local: true) do |form| %>
  <% if oligo.errors.any? %>
    <div class="notification is-warning">
      <h2><%= pluralize(oligo.errors.count, "error") %> prohibited this oligo from being saved:</h2>

      <ul>
        <% oligo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :name %>
    </div>
    <div class="control field-body">
      <%= form.text_field :name %>
      <%= form.text_field :short_name, maxlength: 5, size: 12, placeholder: 'Short Name' %>
    </div>
  </div>
  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :locus %>
    </div>
    <div class="control field-body">
      <%= form.text_field :locus, size: 12 %>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :category %>
    </div>
    <div class="control field-body">
      <%= form.select :category, Oligo.categories.keys, prompt: 'Select' %>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :sequence %>
    </div>
    <div class="control field-body">
      <%= form.text_field :sequence, placeholder: "DNA sequence (GCAT)", maxlength: 50 %>
    </div>
  </div>
  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label 'Reference Position' %>
    </div>
    <div class="control field-body">
      <%= form.number_field :ref_start, placeholder: 'ref start', size: 10 %>
      -
      <%= form.number_field :ref_end, placeholder: 'ref end', size: 10 %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/oligos/edit.html.erb
<h1>Editing Oligo</h1>

<%= render 'form', oligo: @oligo %>

<%= link_to 'Show', @oligo %> |
<%= link_to 'Back', oligos_path %>

app/views/oligos/index.html.erb
<h1 class="title">Oligos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sequence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oligos.each do |oligo| %>
      <tr>
        <td><%= oligo.name %></td>
        <td><%= oligo.sequence %></td>
        <td><%= link_to 'Show', oligo %></td>
        <td><%= link_to 'Edit', edit_oligo_path(oligo) %></td>
        <td><%= link_to 'Destroy', oligo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oligo', new_oligo_path %>

app/views/oligos/new.html.erb
<h1>New Oligo</h1>

<%= render 'form', oligo: @oligo %>

<%= link_to 'Back', oligos_path %>

app/views/oligos/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @oligo.name %>
</p>

<p>
  <strong>Locus:</strong>
  <%= @oligo.locus %>
</p>

<p>
  <strong>Category:</strong>
  <%= @oligo.category %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @oligo.sequence %>
</p>

<p>
  <strong>Reference Positions:</strong>
  <ul>
    <% @oligo.oligo_alignment_positions.each do |pos| %>
      <li><%= pos.organism_taxon.name %> (<%= pos.organism_taxon.reference_accession %>): <%= pos.ref_start %> - <%= pos.ref_end %></li>
    <% end %>
  </ul>
</p>
<hr/>

<%= link_to 'Edit', edit_oligo_path(@oligo) %> |
<%= link_to 'Back', oligos_path %>